BEGIN;
DROP TRIGGER IF EXISTS trg_recording_status_transition ON recordings;
DROP FUNCTION IF EXISTS enforce_recording_status_transition();
ALTER TABLE media_relay_edges      DROP CONSTRAINT IF EXISTS mre_priority_nonneg;
ALTER TABLE media_relay_edges      DROP CONSTRAINT IF EXISTS mre_max_participants_nonneg;
ALTER TABLE media_room_placements  DROP CONSTRAINT IF EXISTS mrp_max_viewers_nonneg;
ALTER TABLE media_room_placements  DROP CONSTRAINT IF EXISTS mrp_max_presenters_nonneg;
ALTER TABLE media_room_placements  DROP CONSTRAINT IF EXISTS mrp_max_participants_nonneg;
ALTER TABLE media_quality_policies DROP CONSTRAINT IF EXISTS mqp_corr_tolerance_ms_nonneg;
ALTER TABLE media_quality_policies DROP CONSTRAINT IF EXISTS mqp_corr_tolerance_pct_range;
ALTER TABLE media_quality_policies DROP CONSTRAINT IF EXISTS mqp_alert_rtt_nonneg;
ALTER TABLE media_quality_policies DROP CONSTRAINT IF EXISTS mqp_alert_jitter_nonneg;
ALTER TABLE media_quality_policies DROP CONSTRAINT IF EXISTS mqp_alert_loss_range;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_bytes_recv_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_bytes_sent_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_bitrate_in_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_bitrate_out_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_rtt_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_jitter_nonneg;
ALTER TABLE media_qos_samples      DROP CONSTRAINT IF EXISTS media_qos_packet_loss_range;
ALTER TABLE breakout_rooms         DROP CONSTRAINT IF EXISTS breakout_rooms_time_limit_nonneg;
ALTER TABLE attachments            DROP CONSTRAINT IF EXISTS attachments_file_size_positive;
ALTER TABLE recording_artifacts    DROP CONSTRAINT IF EXISTS recording_artifacts_duration_nonneg;
ALTER TABLE recording_artifacts    DROP CONSTRAINT IF EXISTS recording_artifacts_packet_count_nonneg;
ALTER TABLE recording_artifacts    DROP CONSTRAINT IF EXISTS recording_artifacts_file_size_nonneg;
ALTER TABLE recordings             DROP CONSTRAINT IF EXISTS recordings_attempts_bounded;
ALTER TABLE recordings             DROP CONSTRAINT IF EXISTS recordings_max_processing_attempts_pos;
ALTER TABLE recordings             DROP CONSTRAINT IF EXISTS recordings_processing_attempts_nonneg;
ALTER TABLE recordings             DROP CONSTRAINT IF EXISTS recordings_file_size_nonneg;
ALTER TABLE recordings             DROP CONSTRAINT IF EXISTS recordings_duration_nonneg;
ALTER TABLE search_index_jobs      DROP CONSTRAINT IF EXISTS search_index_jobs_attempts_bounded;
ALTER TABLE search_index_jobs      DROP CONSTRAINT IF EXISTS search_index_jobs_max_attempts_pos;
ALTER TABLE search_index_jobs      DROP CONSTRAINT IF EXISTS search_index_jobs_attempts_nonneg;
ALTER TABLE guest_invites          DROP CONSTRAINT IF EXISTS guest_invites_use_count_bounded;
ALTER TABLE guest_invites          DROP CONSTRAINT IF EXISTS guest_invites_use_count_nonneg;
ALTER TABLE guest_invites          DROP CONSTRAINT IF EXISTS guest_invites_max_uses_positive;
ALTER TABLE media_quality_alerts   DROP CONSTRAINT IF EXISTS media_quality_alerts_status_check;
ALTER TABLE media_quality_alerts   DROP CONSTRAINT IF EXISTS media_quality_alerts_severity_check;
ALTER TABLE media_quality_alerts   DROP CONSTRAINT IF EXISTS media_quality_alerts_kind_check;
COMMIT;
